package bancojspphp;

import com.google.gson.Gson;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.HttpStatus;
import org.apache.commons.httpclient.methods.PostMethod;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Win 8.1
 */
public class Transaccion extends javax.swing.JFrame {
    Usuario u;

    /**
     * Creates new form Transaccion
     * @param u
     */
    public Transaccion(Usuario u) {
        this.u = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlPagos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRefPago = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClave1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnConfirmPago = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlTransfer = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnConfirmTransfer = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtMonto1 = new javax.swing.JTextField();
        txtClave2 = new javax.swing.JTextField();
        txtClave3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmbBanco = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        pnlPagos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Banco");
        jLabel2.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Realizando Pago");
        jLabel5.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Referencia de Pago:");

        txtRefPago.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtMonto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Monto:");

        txtClave.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Clave:");

        txtClave1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Confirmar clave:");

        btnConfirmPago.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        btnConfirmPago.setText("Confirmar");
        btnConfirmPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmPagoMouseClicked(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlPagosLayout = new javax.swing.GroupLayout(pnlPagos);
        pnlPagos.setLayout(pnlPagosLayout);
        pnlPagosLayout.setHorizontalGroup(
            pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtClave1)
                    .addComponent(txtClave)
                    .addComponent(txtRefPago)
                    .addComponent(txtMonto))
                .addContainerGap())
            .addGroup(pnlPagosLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnConfirmPago)
                .addGap(36, 36, 36)
                .addComponent(btnCancel)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPagosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlPagosLayout.setVerticalGroup(
            pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagosLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRefPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtClave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmPago)
                    .addComponent(btnCancel))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPagosLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Pagos", pnlPagos);

        pnlTransfer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Banco");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Realizando Transferencia");
        jLabel11.setToolTipText("");

        btnConfirmTransfer.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        btnConfirmTransfer.setText("Confirmar");
        btnConfirmTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmTransferMouseClicked(evt);
            }
        });

        btnCancel1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        btnCancel1.setText("Cancelar");
        btnCancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancel1MouseClicked(evt);
            }
        });
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Monto:");

        txtMonto1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtClave2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtClave3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Confirmar clave:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Clave:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Número de Cuenta:");

        txtCuenta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Banco Destino:");

        cmbBanco.setEditable(true);
        cmbBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bancolombia", "Davivienda", "Banco Popular", "Etc" }));

        javax.swing.GroupLayout pnlTransferLayout = new javax.swing.GroupLayout(pnlTransfer);
        pnlTransfer.setLayout(pnlTransferLayout);
        pnlTransferLayout.setHorizontalGroup(
            pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTransferLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnConfirmTransfer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel1)
                .addGap(58, 58, 58))
            .addGroup(pnlTransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTransferLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pnlTransferLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtClave3)
                    .addComponent(txtClave2)
                    .addComponent(txtCuenta)
                    .addComponent(txtMonto1)
                    .addComponent(cmbBanco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlTransferLayout.setVerticalGroup(
            pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTransferLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(cmbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtClave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtClave3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pnlTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel1)
                    .addComponent(btnConfirmTransfer))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Transferencias", pnlTransfer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void btnConfirmPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmPagoMouseClicked
        // TODO add your handling code here:
        //Realizar el pago de un servicio
        String url = "http://localhost:8080/bancoJSPWeb/faces/hacerpago.jsp";
        Gson gson = new Gson();
        HttpClient cliente = new HttpClient();
        
        String refPago = this.txtRefPago.getText();
        float monto = Float.parseFloat(this.txtMonto.getText());
        String clave = this.txtClave.getText();
        String clave2 = this.txtClave1.getText();
        if (!clave.equals(clave2)) {
            System.out.println("Las claves no coinciden");
            return;
        }
        
        PostMethod metodo = new PostMethod(url);
        metodo.addParameter("refpago", refPago);
        metodo.addParameter("monto", String.valueOf(monto));
        metodo.addParameter("cuenta", u.getCuenta());
        metodo.addParameter("clave", clave);
        BufferedReader br;
        
        try{
            int codRetorno = cliente.executeMethod(metodo);
            
            if (codRetorno == HttpStatus.SC_NOT_IMPLEMENTED){
                System.out.println("Operacion no implementada");
                System.out.println("Respuesta obtenida: "+metodo.getResponseBodyAsString());
            }
            else if (codRetorno == HttpStatus.SC_OK){
                String json = "";
                br = new BufferedReader(new InputStreamReader(metodo.getResponseBodyAsStream()));
                String linea = br.readLine();
                while (linea != null){
                    if (!linea.trim().isEmpty()){
                        json += linea;
                    }
                }
                
                if (json.contains("Usuario no registrado") || json.contains("Servicio inexistente")){
                    System.out.println("Error: "+json);
                }
                else {
                    u = gson.fromJson(json, Usuario.class);
                    InicioUsuario iu = new InicioUsuario(u);
                }
            }
        } catch (IOException ex) {
            System.out.println("Error al conectar con el servidor");
        }
    }//GEN-LAST:event_btnConfirmPagoMouseClicked

    private void btnConfirmTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmTransferMouseClicked
        // TODO add your handling code here:
        //Realizar una transferencia
        String url = "http://localhost:8080/bancoJSPWeb/faces/hacertransfer.jsp";
        Gson gson = new Gson();
        HttpClient cliente = new HttpClient();
        
        String banco = this.cmbBanco.getItemAt(this.cmbBanco.getSelectedIndex());
        String cuentaex = this.txtCuenta.getText();
        float monto = Float.parseFloat(this.txtMonto.getText());
        String clave = this.txtClave.getText();
        String clave2 = this.txtClave1.getText();
        if (!clave.equals(clave2)) {
            System.out.println("Las claves no coinciden");
            return;
        }
        
        PostMethod metodo = new PostMethod(url);
        metodo.addParameter("banco", banco);
        metodo.addParameter("cuentaex", cuentaex);
        metodo.addParameter("monto", String.valueOf(monto));
        metodo.addParameter("cuenta", u.getCuenta());
        metodo.addParameter("clave", clave);
        BufferedReader br;
        
        try{
            int codRetorno = cliente.executeMethod(metodo);
            
            if (codRetorno == HttpStatus.SC_NOT_IMPLEMENTED){
                System.out.println("Operacion no implementada");
                System.out.println("Respuesta obtenida: "+metodo.getResponseBodyAsString());
            }
            else if (codRetorno == HttpStatus.SC_OK){
                String json = "";
                br = new BufferedReader(new InputStreamReader(metodo.getResponseBodyAsStream()));
                String linea = br.readLine();
                while (linea != null){
                    if (!linea.trim().isEmpty()){
                        json += linea;
                    }
                }
                
                if (json.contains("Usuario no registrado") || json.contains("Servicio inexistente")){
                    System.out.println("Error: "+json);
                }
                else {
                    u = gson.fromJson(json, Usuario.class);
                    InicioUsuario iu = new InicioUsuario(u);
                }
            }
        } catch (IOException ex) {
            System.out.println("Error al conectar con el servidor");
        }
    }//GEN-LAST:event_btnConfirmTransferMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        InicioUsuario iu = new InicioUsuario(u);
        iu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancel1MouseClicked
        // TODO add your handling code here:
        InicioUsuario iu = new InicioUsuario(u);
        iu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaccion(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnConfirmPago;
    private javax.swing.JButton btnConfirmTransfer;
    private javax.swing.JComboBox<String> cmbBanco;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlPagos;
    private javax.swing.JPanel pnlTransfer;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtClave1;
    private javax.swing.JTextField txtClave2;
    private javax.swing.JTextField txtClave3;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMonto1;
    private javax.swing.JTextField txtRefPago;
    // End of variables declaration//GEN-END:variables
}
